apiVersion: apps/v1
kind: Deployment
metadata:
  name: argojk73
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argojk73
  template:
    metadata:
      labels:
        app: argojk73
    spec:
      containers:
        - name: argojk73
          image: jaykumark7/argojk73:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000