apiVersion: apps/v1
kind: Deployment
metadata:
  name: argojk75
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argojk75
  template:
    metadata:
      labels:
        app: argojk75
    spec:
      containers:
        - name: argojk75
          image: jaykumark7/argojk75:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000