apiVersion: apps/v1
kind: Deployment
metadata:
  name: argojk76
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argojk76
  template:
    metadata:
      labels:
        app: argojk76
    spec:
      containers:
        - name: argojk76
          image: jaykumark7/argojk76:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000