apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetestest1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetestest1
  template:
    metadata:
      labels:
        app: kubernetestest1
    spec:
      containers:
        - name: kubernetestest1
          image: jaykumark7/kubernetestest1:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000