apiVersion: v1
kind: Service
metadata:
  name: kubernetestest1
spec:
  selector:
    app: kubernetestest1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP