apiVersion: apps/v1
kind: Deployment
metadata:
  name: argojk77
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argojk77
  template:
    metadata:
      labels:
        app: argojk77
    spec:
      containers:
        - name: argojk77
          image: jaykumark7/argojk77:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000