apiVersion: apps/v1
kind: Deployment
metadata:
  name: february-demo19th
spec:
  replicas: 1
  selector:
    matchLabels:
      app: february-demo19th
  template:
    metadata:
      labels:
        app: february-demo19th
    spec:
      containers:
        - name: february-demo19th
          image: jaykumark7/february-demo19th:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000