apiVersion: v1
kind: Service
metadata:
  name: february-demo19th
spec:
  selector:
    app: february-demo19th
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP