apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigtest1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigtest1
  template:
    metadata:
      labels:
        app: bigtest1
    spec:
      containers:
        - name: bigtest1
          image: jaykumark7/bigtest1:1.0.7
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000