apiVersion: apps/v1
kind: Deployment
metadata:
  name: argojk74
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argojk74
  template:
    metadata:
      labels:
        app: argojk74
    spec:
      containers:
        - name: argojk74
          image: jaykumark7/argojk74:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000