apiVersion: apps/v1
kind: Deployment
metadata:
  name: argojk72
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argojk72
  template:
    metadata:
      labels:
        app: argojk72
    spec:
      containers:
        - name: argojk72
          image: jaykumark7/argojk72:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000