apiVersion: v1
kind: Service
metadata:
  name: kubernetestest2
spec:
  selector:
    app: kubernetestest2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP